### ISSUE TITLE
only plain text in the wiki description is supported by taginfo

### ISSUE THREAD

**Issue by matkoniecz** [taginfo/taginfo#171]
For example http://taginfo.openstreetmap.org/tags/barrier=swing_gate#wiki has

> No English language description for this tag in the wiki. (See also the "Wiki" tab.)

but there is http://wiki.openstreetmap.org/wiki/Tag:barrier%3Dswing_gate with description in the template.

**Comment by joto** [comment]
Anything other than plain text in the description isn't supported by taginfo. Here there is a link `[[Tag:barrier=lift gate|lift gate]]` embedded in the description that taginfo can't handle. You can call this a bug and I might improve this someday, but I would still argue that the description should be a plain text that works outside the wiki context.

**Comment by Hufkratzer** [comment]
Can you support'=' in descriptions? Compare wiki discussion 
[Proposal: auto-convert description Tag:xxx=yyy into a link
](https://wiki.openstreetmap.org/wiki/Talk:Data_items#Proposal:_auto-convert_description_Tag:xxx.3Dyyy_into_a_link) I think '=' is the reason way descriptions with something like "tag:a=b" are not shown in taginfo.  
'+', '-', '*', '/' and ':' are supported.

**Comment by 1ec5** [comment]
> Can you support '=' in descriptions?

See #199.

**Comment by jeisenbe** [comment]
I have also noticed that the description is broken by the addition of `=` (equals sign).

For example: [Tag:route=ski](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Dski) description: "A nordic or alpine ski route - see also the approved tag route=piste"

In these cases, as with others, mappers want to mention another tag in the description, since it might be easily confused with this tag. 

Another case, which I just changed, was power=plant which mentioned that it should include one or more power=generator features inside - I had to remove the equals sign to get the description to display, but the current text "including ... power generator features" is less clear than "including ... power=generator features" where it is certain that this is the key=value of the tag.

Also, text in the format "Key:key" or "Tag:key=value" causes the same problems, e.g. [Tag:route=railway](https://wiki.openstreetmap.org/wiki/Tag%3Aroute%3Drailway) description: "The route of a railway (eg the Channel Tunnel). Not to be confused with the route of a train service (see Tag:route=train)."

I understand that we should not include wiki markup like {{tag|route|train}} in the descriptions, and I can understand if "Key:route" is a problem since it refers to a wiki page title rather than something in the database. 

But I think we should be able to use text like "not to be confused with route=train" or "must include at least one power=generator" in the description.

**Comment by jeisenbe** [comment]
Another issue is with deprecated tags. These get a description like [Tag:leisure=common](https://wiki.openstreetmap.org/wiki/Tag%3Aleisure%3Dcommon) "Using this tag is discouraged, use landuse=* or leisure=*, possibly with designation=common instead." 

Perhaps it is intentional for taginfot to not show a definition with these? 

But it looks odd on taglists.

**Comment by RichMar** [comment]
Hi, I'm also advocating that taginfo be able to work with at least the dot "." and a colon ":".
I would like to search for expressions assigned to the image from commons, eg "File: Kreutz bei Pottenhofen.jpg"

**Comment by Hufkratzer** [comment]
I came across a case where a description with '='  (*"A tag to refine an object mapped with **tag:amenity=shelter**"*) shows up in taginfo, see https://taginfo.openstreetmap.org/keys/shelter_type#wiki. 
I wonder if something has changed.

**Comment by 1ec5** [comment]
That syntax comes from the source code of [the corresponding wiki page](https://wiki.openstreetmap.org/wiki/Key%3Ashelter_type). [The infobox template](https://wiki.openstreetmap.org/wiki/Template:KeyDescription) can convert that syntax to a key=value link on the wiki, but taginfo is scraping the source code of each wiki page, not its rendered output.

**Comment by Hufkratzer** [comment]
Thanks, but I know that and this was not the problem. The problem was, as described above ([here](https://github.com/taginfo/taginfo/issues/171#issuecomment-500202622) and [here](https://github.com/taginfo/taginfo/issues/171#issuecomment-594943110)), that if a description contained certain characters (especially '=') that taginfo didn't accept it and only showed a blank line.  It seems to me that this problem has disappeared now.

**Comment by maro-21** [comment]
I agree with joto, that the descriptions should contain only plain text. I corrected many such descriptions on the Wiki and I still correct them from time to time. Almost all, if not all, are gone. So I think this issue can be closed because this problem no longer occurs.

**Comment by joto** [comment]
There are still [a few cases](https://taginfo.openstreetmap.org/taginfo/wiki-problems#list) with `[]` or `<>` characters in the text which interfere with parsing, because they are special characters in the Mediawiki.

**Comment by Hufkratzer** [comment]
@maro-21 : 
> I agree with joto, that the descriptions should contain only plain text. I corrected many such descriptions on the Wiki and I still correct them from time to time. Almost all, if not all, are gone. So I think this issue can be closed because this problem no longer occurs.

In the descriptions there are ‘tag:key=value’s, which is not plain text. They are displayed as links in the OSM wiki. Do you leave them alone?

**Comment by maro-21** [comment]
> There are still [a few cases](https://taginfo.openstreetmap.org/taginfo/wiki-problems#list) with `[]` or `<>` characters in the text which interfere with parsing, because they are special characters in the Mediawiki.

But they are also correct punctuation characters.
`[[sth]]` is Mediawiki syntax, not `[]` and not single `<` or `>`.

`Eine Anhäufung von gerundeten Geröllen (> 2 mm)` is still a plain text.

But these are the issues from the validator. What is there to do on the code side of Taginfo?

This issue no longer occurs because it is not true that "only plain text in the wiki description is supported by taginfo" as stated in 2016. See https://taginfo.openstreetmap.org/tags/natural=shingle#wiki that this description is properly displayed.


> In the descriptions there are ‘tag:key=value’s, which is not plain text. They are displayed as links in the OSM wiki. Do you leave them alone?

This is the correct formatting as stated in the documentation of the `description` field.

**Comment by matkoniecz** [comment]
> This is the correct formatting as stated in the documentation of the description field.

this is just a different formatting of links, and still not a plain text (for some reason people were moving to this link format from normal link format, but it is still formatting code)

**Comment by joto** [comment]
@maro-21 External links in Mediawiki just use single `[]` and `<>` are used for HTML or some other special syntax. There is just no way taginfo can parse the full Mediawiki syntax, it is just too massive and convoluted. So until somebody has a better idea how to solve this we'll have to live with that restriction.

**Comment by maro-21** [comment]
> @maro-21 External links in Mediawiki just use single `[]` and `<>` are used for HTML or some other special syntax.

You're right.

> There is just no way taginfo can parse the full Mediawiki syntax, it is just too massive and convoluted. So until somebody has a better idea how to solve this we'll have to live with that restriction.

But what is there to do on the code side of Taginfo? This issue is from 2016 and the descriptions are displayed in Taginfo, even if they have `[` or `>`.

We avoid [[links]] in descirptions and we don't want taginfo to display them as links even if there is such a description with links.

Can you agree that `Eine Anhäufung von gerundeten Geröllen (> 2 mm)` is a plain text?

**Comment by joto** [comment]
Sorry, @maro-21, misunderstanding on my part. I thought these descriptions didn't show up in taginfo, but they do, so, yes, it all looks good now and we can close this issue.

If anybody has any issues like this again: Please open a new issue as this one is confusing enough. :-)
